image: continuumio/anaconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate ctaarchiveenv
  - conda install numpy # protobuf astropy
  #- pip install Cython
  #- pip install https://github.com/cta-sst-1m/protozfitsreader/archive/v1.4.1.tar.gz
  - docker info
tests:
  stage: test
  script:
    - python -m unittest discover -v


after_script:
  #build docker image
  docker build -t gitlab-registry.in2p3.fr/frederic.gillardo1/ctaarchive

  #upload docker image ot registry
  - docker push gitlab-registry.in2p3.fr/frederic.gillardo1/ctaarchive