image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

stages:
  - init
  - test
  - publish

init:
  stage: init
  script:

test:
  stage: test
  script:
    - docker build -t gitlab-registry.in2p3.fr/cta-lapp/cta-archive .
    - docker run gitlab-registry.in2p3.fr/cta-lapp/cta-archive python -m unittest discover -v 

publish:
  stage: publish
  script:
    - docker build -t gitlab-registry.in2p3.fr/cta-lapp/cta-archive .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry.in2p3.fr
    - docker push gitlab-registry.in2p3.fr/cta-lapp/cta-archive
